ui tweaks to auth page
bcgov/vc-authn-oidc pull request #116
Opened 2021-01-04 23:42 UTC by wadeking98

2021-01-04 23:49 UTC, wadeking98 commented
![ui_changes](https://user-images.githubusercontent.com/36937407/103591227-5e61c180-4ea4-11eb-9db4-ae3765e1287e.png)

2021-01-05 17:24 UTC, esune commented
Added @swcurran to the review for a visual check.

What I would tweak:
- I would leave the "authentication required" header at the same level and color of the rest of the background
- I personally don't like having text/buttons above the QR code (I know this is what the mockup showed), and would personally like it better if the QR code and button were after the header (as before), and the descriptive text at the bottom.

Let's see what @swcurran thinks, I thin this is a mix of preferences and what I think would be more usable across desktop and mobile devices, but I am not a usability expert so...

2021-01-08 21:18 UTC, wadeking98 commented
tweaked UI
![qrchanges2](https://user-images.githubusercontent.com/36937407/104065062-efda7780-51b3-11eb-82d6-d058c3495825.png)

2021-01-08 22:39 UTC, esune commented
@swcurran can you please confirm this works for you and merge?

2021-01-09 00:22 UTC, swcurran requested changes

2021-01-09 00:22 UTC, swcurran commented on oidc-controller/src/VCAuthn/Views/Authorize/Authorize.cshtml
> +           To authenticate, present your digital credential by using your identity wallet phone app to scan the QR code below</p>
The QR code is above now, right?  The "below" should read "above"?

2021-01-12 21:29 UTC, esune approved these changes

2021-01-12 21:30 UTC, merged