Add responsive sizing of VCAuthn login page for mobile devices
bcgov/vc-authn-oidc pull request #430
Opened 2024-03-05 20:47 UTC by Gavinok

This PR resolves #420 using media queries as well as bootstrap.

Here is the new desktop view

![2024-03-05_12-31-10](https://github.com/bcgov/vc-authn-oidc/assets/34443260/9610b4e4-074b-49c3-a16b-78d083097939)

![2024-03-05_12-28-05](https://github.com/bcgov/vc-authn-oidc/assets/34443260/af1d0559-9b3e-4871-94ec-57e804495dde)

To ensure uniform rendering of the boarder it no longer uses a dedicated svg and instead uses CSS boarders

On mobile devices the card style is removed and instead the entire screen is used to make the most of the smaller displays.

![2024-03-05_12-34-14](https://github.com/bcgov/vc-authn-oidc/assets/34443260/c74157b8-573d-4d7b-8562-e42359f75936)

![2024-03-05_12-44-45](https://github.com/bcgov/vc-authn-oidc/assets/34443260/ca7b3e98-3b82-4028-b2db-c15475b5c0a9)

2024-03-05 23:52 UTC, Gavinok commented
With the removal of media queries the css is simplified. I have also migrated the button css to make use of bootstrap. Here is the updated look on desktop

![2024-03-05_15-50-38](https://github.com/bcgov/vc-authn-oidc/assets/34443260/d888723a-4b9c-46b7-bbe3-a3f1b044a01b)

and on mobile

![2024-03-05_15-51-44](https://github.com/bcgov/vc-authn-oidc/assets/34443260/08ba0045-76f0-4ab2-bef8-20eb2f63558d)

2024-03-06 18:58 UTC, esune commented
@Gavinok can you resolve the conflicts - likely with code from the last merged PR?

2024-03-06 19:04 UTC, Gavinok commented
@esune Ready for review

2024-03-06 19:15 UTC, Gavinok commented
@esune resolved the conflict

2024-03-06 21:35 UTC, esune submitted a review, later dismissed
LGTM based on screenshots and what demonstrated during live review.

2024-03-06 21:51 UTC, loneil requested changes
Holding this as deep link is no longer delivering request message (working on main fine)

2024-03-06 21:53 UTC, loneil commented
@Gavinok see comment above, not working with form action, needs to be an href link I believe.

Probably: https://stackoverflow.com/questions/45542773/how-to-style-an-anchor-as-a-button-in-bootstrap-4

2024-03-06 22:02 UTC, loneil commented on oidc-controller/api/templates/verified_credentials.html
> +          >
Formatting

2024-03-06 22:06 UTC, loneil commented
Can we do some additional tweaks to the widths of the "header-desc" (and possibly other) containers?

They're thinner in which is crowding texts.

Existing:
![image](https://github.com/bcgov/vc-authn-oidc/assets/17445138/e4db431c-956f-4763-a6bc-cf66b580f3a6)

Current:

Initial text (also could use a top margin here when opening the "other device" section)
![image](https://github.com/bcgov/vc-authn-oidc/assets/17445138/78df7d77-476d-4d87-a049-9a9a78433b96)

Declined
![image](https://github.com/bcgov/vc-authn-oidc/assets/17445138/ffbb9a93-068f-4836-92bc-1befec12dbd6)
(Probably same with approved and expired states)

Scanned mask over the qr code is thinner
![image](https://github.com/bcgov/vc-authn-oidc/assets/17445138/c63e541e-c1bb-4901-b736-13d707ae19a8)

2024-03-06 22:07 UTC, Gavinok commented
> @Gavinok see comment above, not working with form action, needs to be an href link I believe.
> 
> Probably: https://stackoverflow.com/questions/45542773/how-to-style-an-anchor-as-a-button-in-bootstrap-4

Dang that was what made is able to remove all that custom button CSS :(

2024-03-06 22:11 UTC, esune commented
I'm wondering if we should tackle the UI redesign/tweaks as part of the full move to Bootstrap, rather than potentially do the work twice? https://github.com/bcgov/vc-authn-oidc/issues/431

2024-03-06 22:13 UTC, loneil commented
> > @Gavinok see comment above, not working with form action, needs to be an href link I believe.
> > Probably: https://stackoverflow.com/questions/45542773/how-to-style-an-anchor-as-a-button-in-bootstrap-4
> 
> Dang that was what made is able to remove all that custom button CSS :(

No should just need to change `button` to `a` I just did that on my local and it worked.

2024-03-06 22:14 UTC, Gavinok commented
> Reference in new issue
> Edit
> Hide
> Delete

It was more to do with the css not indicating the button was disabled but I was able to work around this anyways

2024-03-06 22:20 UTC, Gavinok commented
@loneil is it just me or does the qr code expire extremely fast now? Did I make a change that could effect that?

2024-03-06 22:29 UTC, Gavinok commented
> Can we do some additional tweaks to the widths of the "header-desc" (and possibly other) containers?
> 
> They're thinner in which is crowding texts.
> 
> Existing: ![image](https://private-user-images.githubusercontent.com/17445138/310678565-e4db431c-956f-4763-a6bc-cf66b580f3a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NjQwMTcsIm5iZiI6MTcwOTc2MzcxNywicGF0aCI6Ii8xNzQ0NTEzOC8zMTA2Nzg1NjUtZTRkYjQzMWMtOTU2Zi00NzYzLWE2YmMtY2Y2NmI1ODBmM2E2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDIyMjE1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzNDdmNTU2Zjk3MTJlMDc3ZGVjOGE4ZjQ3OGQzMzgwZmNkYjU1ZmM3MGU0ZDBkMWFkNmI3NzU3ZGJlZWYzMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rfzM_O6aTrSymEtGD3rLiqj1vCFAekG1T8ybGbaRn0k)
> 
> Current:
> 
> Initial text (also could use a top margin here when opening the "other device" section) ![image](https://private-user-images.githubusercontent.com/17445138/310678736-78df7d77-476d-4d87-a049-9a9a78433b96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NjQwMTcsIm5iZiI6MTcwOTc2MzcxNywicGF0aCI6Ii8xNzQ0NTEzOC8zMTA2Nzg3MzYtNzhkZjdkNzctNDc2ZC00ZDg3LWEwNDktOWE5YTc4NDMzYjk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDIyMjE1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5NzhhMjRkMzgyMjk4MzQxNDdiNTAwOWFhMTNjMGIyOTE3ODdmZjE4ODFiMDQ0ZjJhNzU3NWYwNmViMTI5NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.isFRZDPCTLe09QPujZ6xEczzdvABFbHl48fh8qT8PZA)
> 
> Declined ![image](https://private-user-images.githubusercontent.com/17445138/310678793-ffbb9a93-068f-4836-92bc-1befec12dbd6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NjQwMTcsIm5iZiI6MTcwOTc2MzcxNywicGF0aCI6Ii8xNzQ0NTEzOC8zMTA2Nzg3OTMtZmZiYjlhOTMtMDY4Zi00ODM2LTkyYmMtMWJlZmVjMTJkYmQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDIyMjE1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmNWUwMzUzNjIwNTY5NTFlYmU4NGEwNWE1YzdmNjk3MThmYmMyNDA4YmEzODFhMDk0YTkyYjRkZWUyYjk4M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q-71u3uU3tmtcpLwk6fdOdgfsnRDKpqgbX3AK7bZUy8) (Probably same with approved and expired states)
> 
> Scanned mask over the qr code is thinner ![image](https://private-user-images.githubusercontent.com/17445138/310678932-c63e541e-c1bb-4901-b736-13d707ae19a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NjQwMTcsIm5iZiI6MTcwOTc2MzcxNywicGF0aCI6Ii8xNzQ0NTEzOC8zMTA2Nzg5MzItYzYzZTU0MWUtYzFiYi00OTAxLWI3MzYtMTNkNzA3YWUxOWE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDIyMjE1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1M2Q5YmRjMDlkYWNhMTgzNWNiZTQxMDVjOGM1MjI5NWNkMTJjM2FhZjZhYzgzNDIzNWRmMDQyOTliYmY3NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yIRFJSTPB2Z2ul7s6jbad1Ao9bsOT-NQI_quj9VyfKg)

I have just updated this. There should be a little more space. I figured we should add some line breaks for more consistent text formatting while I was at it.

2024-03-11 20:47 UTC, esune approved these changes

2024-03-18 17:54 UTC, loneil approved these changes
Works for me, should be good to deploy for more device testing in dev. Can refine further with bootstrap framework.

2024-03-18 17:55 UTC, merged